### ISSUE TITLE
首页样式调整

### ISSUE THREAD

**Issue by ruiming** [ruiming/onlinejudge-frontend#1]
参照圆圆设计图进行主页样式调整

**Comment by ruiming** [comment]
@smilehuhuhuhu  @xxxxxin 你们可以分工开始写下这个页面，不清楚的地方可以相互讨论下或者问我，按照圆圆的设计图做调整。记得按照我发的开发规范来进行。尽量这周末前完成。收到在下面回复下哦～

**Comment by cowex** [comment]
收到。不过喵我要写吗？还是画3.0？

在 2017年4月10日 下午9:43，ruiming <notifications@github.com>写道：

**Comment by ruiming** [comment]
@cowex 你不用写，不过上次让你改的你改好了吗 =.=
